SELECT TOP (1000) [Id]
      ,[Username]
      ,[PasswordHash]
      ,[Role]
      ,[StudentId]
      ,[CreatedAt]
      ,[CreatedBy]
      ,[LastModifiedAt]
      ,[LastModifiedBy]
      ,[IsDeleted]
      ,[DeletedAt]
  FROM [StudentMgmtDb].[dbo].[Users]